### ISSUE TITLE
首页出现滚动条

### ISSUE THREAD

**Issue by MengJiXiaoCaiNiao** [gcpaas/gc-starter-bigscreen-ui#1]
### 问题描述

进入到大屏页面 /pages 地址时，笔记本电脑看到右侧有滚动条

### 重现链接

http://192.168.59.45:9080/bigScreen/#/pages

### 重现步骤

1. 进入到 http://192.168.59.45:9080/bigScreen/#/pages页面
2. 创建大屏
3. 查看右侧是否有大屏

### 预期行为

我期望看不到滚动条，滚动条应该在大屏里面

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
- gc-starter-bigscreen-ui 版本: [1.0.0  ]

### 屏幕截图或视频（可选）

<img width="1440" alt="2023-05-17_09-09-42" src="https://github.com/gcpaas/gc-starter-bigscreen-ui/assets/133212684/46dc452a-56e2-427a-bfa8-60512ef40ad5">

**Comment by HunterXing** [comment]
[fix: 首页出现滚动条 #1](https://github.com/gcpaas/gc-starter-bigscreen-ui/commit/42f15e8701ed55ca3684c28cabb2bb715f632b43)
