### ISSUE TITLE
支持历史记录回退与撤销

### ISSUE THREAD

**Issue by gccloud300520** [gcpaas/gc-starter-bigscreen-ui#3]
大屏设计器新增【撤回】操作，历史操作记录查询，历史存储到前端

**Comment by HunterXing** [comment]
closed with https://github.com/gcpaas/gc-starter-bigscreen-ui/commit/7dff472bf2e3036145ece27903c3886deecea272 https://github.com/gcpaas/gc-starter-bigscreen-ui/commit/09b0e6e2e670ab36e48f6fb998dd0df273e60a61
